# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reasoning',
            field=models.CharField(default='Why not?', max_length=400),
        ),
    ]
